### ISSUE TITLE
키워드 쿠폰을 등록할 수 있다

### ISSUE THREAD

**Issue by JamieShin0201** [CodeSoom/DDD-Kurly-Clone-Promotion#36]
url: /coupons 
parameter: keyword

**Comment by etff** [comment]
https://github.com/CodeSoom/DDD-Kurly-Clone-Promotion/issues/37#issue-1032525107 어떤점이 다른건가요? 🤔

**Comment by hannut91** [comment]
키워드 쿠폰을 등록한다는 의미가 키워드 쿠폰을 발행한다는 의미와 같습니다 ㅎㅎ 중복되어 이 이슈는 닫을게요
